package main

import "fmt"

func main() {
    
    // without update original slice value
    vals := []int{4, 2, 6}
    for _, v := range vals {
        v--
    }
    fmt.Println(vals)
    
    // updating original slice value
    for i, v := range vals {
        vals[i] = v - 1
    }
    fmt.Println(vals)
    
    // Just only looping without be interested in any value generated by interation
    for range []int{1,1,1,1} {
        fmt.Println("Looping")
    }
}